import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

// Load signing config from local.properties (populated by scripts/fetch-signing.sh).
// Absent in CI dev builds; release builds without it fall back to the debug key.
val signingProps = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}

android {
    namespace = "com.theermite.hoso"
    compileSdk = 36

    // GlitchTip/Sentry DSN — injected from local.properties (gitignored),
    // never committed. Empty by default so open-source builds and forks
    // report nowhere (Sentry no-ops on a blank DSN). Debug builds also get
    // an empty DSN below so local dev never pollutes the GlitchTip project.
    val sentryDsn = signingProps.getProperty("sentry.dsn", "")

    defaultConfig {
        applicationId = "com.theermite.hoso"
        minSdk = 29
        targetSdk = 35
        versionCode = 12
        versionName = "1.1.0"

        manifestPlaceholders["sentryDsn"] = sentryDsn
    }

    signingConfigs {
        create("release") {
            val storeFilePath = signingProps.getProperty("signing.storeFile")
            if (storeFilePath != null) {
                storeFile = file(storeFilePath)
                storePassword = signingProps.getProperty("signing.storePassword")
                keyAlias = signingProps.getProperty("signing.keyAlias")
                keyPassword = signingProps.getProperty("signing.keyPassword")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = if (signingProps.getProperty("signing.storeFile") != null) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
        debug {
            // Never report from local dev builds to the shared GlitchTip
            // project — keep the crash feed limited to real users.
            manifestPlaceholders["sentryDsn"] = ""
        }
    }

    buildFeatures {
        viewBinding = true
    }

    lint {
        // Release builds must fail on lint errors. NewApi is elevated to
        // fatal so a call above minSdk (e.g. an API 30 method on minSdk 29)
        // blocks the release instead of shipping a launch crash — this is
        // how the getMaximumWindowMetrics() API-29 crash slipped through.
        abortOnError = true
        checkReleaseBuilds = true
        warningsAsErrors = false
        fatal += "NewApi"
        // PropertyEscape only inspects .properties files; our sole match is
        // local.properties — gitignored, machine-specific, generated by
        // scripts/fetch-signing.sh. Its Windows key-store path is never
        // shipped, so escaping it is not an app-quality signal.
        disable += "PropertyEscape"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.lifecycle.runtime)
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.viewpager2)

    implementation(libs.streampack.core)
    implementation(libs.streampack.services)
    implementation(libs.streampack.rtmp)

    implementation(libs.sentry.android)

    testImplementation(libs.junit)
    testImplementation(libs.org.json)
}
